name: Java CI/CD with Maven

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      RUN_GIT_CHECKOUT:
        type: boolean
        default: true
      RUN_MVN_COMPILE:
        type: boolean
        default: true
      RUN_MVN_TEST:
        type: boolean
        default: true
      RUN_MVN_PACKAGE:
        type: boolean
        default: true
      RUN_NEXUS_UPLOAD:
        type: boolean
        default: true
      RUN_SONAR:
        type: boolean
        default: true
      RUN_OWASP:
        type: boolean
        default: true
      RUN_DOCKER_BUILD:
        type: boolean
        default: true
      RUN_TRIVY:
        type: boolean
        default: true
      RUN_GIT_CHECKOUT1:
        type: boolean
        default: true
      RUN_DEPLOY_CONTAINER:
        type: boolean
        default: true

permissions:
  contents: read
  packages: write

env:
  APP_VERSION: 1.0.${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        if: inputs.RUN_GIT_CHECKOUT
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set Build Version
        run: |
          mvn versions:set \
            -DnewVersion=${APP_VERSION} \
#            -DgenerateBackupPoms=false

      - name: Maven Compile
        if: inputs.RUN_MVN_COMPILE
        run: mvn compile

      - name: Maven Test
        if: inputs.RUN_MVN_TEST
        run: mvn test

      - name: Maven Package
        if: inputs.RUN_MVN_PACKAGE
        run: mvn clean package -DskipTests

      - name: Nexus Upload
        if: inputs.RUN_NEXUS_UPLOAD
        run: mvn deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USER }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

  security-and-build:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [sonar, owasp, docker, trivy]

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: SonarQube Analysis
        if: matrix.task == 'sonar' && inputs.RUN_SONAR
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectName=Multi-Tier-BankApp-CI \
            -Dsonar.projectKey=Multi-Tier-BankApp-CI \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=$SONAR_TOKEN

      - name: OWASP Dependency Check
        if: matrix.task == 'owasp' && inputs.RUN_OWASP
        run: |
          docker run --rm \
            -v $(pwd):/src \
            owasp/dependency-check \
            --scan /src \
            --format XML

      - name: Docker Build & Push
        if: matrix.task == 'docker' && inputs.RUN_DOCKER_BUILD
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ashu290996/bankapp:${{ env.APP_VERSION }}
            ashu290996/bankapp:latest
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Trivy Scan
        if: matrix.task == 'trivy' && inputs.RUN_TRIVY
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ashu290996/bankapp:${{ env.APP_VERSION }}
          format: table

  deploy:
    needs: security-and-build
    runs-on: ubuntu-latest
    if: inputs.RUN_DEPLOY_CONTAINER

    steps:
      - name: Checkout CD Repo
        uses: actions/checkout@v4
        with:
          repository: ashu290996/Multi-Tier-BankApp-CD
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f bankapp/bankapp-ds.yml -n prod
          kubectl apply -f database/database-ds.yml -n prod
          kubectl set image deployment bankapp-deployment \
            bankapp=ashu290996/bankapp:${{ env.APP_VERSION }} -n prod
